name: Create-file-on-lightsail

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run it manually like in your screenshot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Connected to the Lightsail successfully!"
            cd /var/www/html
            git pull origin main